name: kronik_hasta_takip
description: "Kronik hastaların takibi için mobil uygulama"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.30.4
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.12
  firebase_core: ^2.25.4
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.13.1   # 👈 BUNU EKLE
  fl_chart: ^0.64.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  smooth_page_indicator: ^1.1.0
  multi_select_flutter: 4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/adsiz_tasarim_14.png
    - images/eye_icon.png
    - images/frame_56.png
    - images/frame_59.png
    - images/frame_60.png
    - images/frame_63.png
    - images/frame_64.png
    - images/frame_65.png
    - images/frame_66.png
    - images/frame_67.png
    - images/frame_68.png
    - images/frame_69.png
    - images/frame_82.png
    - images/frame_83.png
    - images/frame_84.png
    - images/frame_106.png
    - images/frame_107.png
    - images/koyu_rectangle.png
    - images/uzun_rectangle.png
    - images/yesil_rectangle.png
    - images/adim.png
    - images/ayak.png
    - images/kalp.png
    - images/person.png
    - images/tansiyon.png
    - images/arka_plan.png
    - images/kan.png
    - images/stressed.png
    - images/sicaklik.png
    - images/ana_sayfa_arkaplan.png
